donate:
    resource: "@DonateBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

events:
    resource: "@EventsBundle/Resources/config/routing.yml"
    prefix:   /home

app:
    resource: '@AppBundle/Controller/'
    type: annotation
